/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bj58.spider.faiss;

public class IndexIVF extends Index implements Level1Quantizer {
  private transient long swigCPtr;

  protected IndexIVF(long cPtr, boolean cMemoryOwn) {
    super(swigfaissJNI.IndexIVF_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexIVF obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_IndexIVF(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long Level1Quantizer_GetInterfaceCPtr() {
    return swigfaissJNI.IndexIVF_Level1Quantizer_GetInterfaceCPtr(swigCPtr);
  }

  public void setInvlists(InvertedLists value) {
    swigfaissJNI.IndexIVF_invlists_set(swigCPtr, this, InvertedLists.getCPtr(value), value);
  }

  public InvertedLists getInvlists() {
    long cPtr = swigfaissJNI.IndexIVF_invlists_get(swigCPtr, this);
    return (cPtr == 0) ? null : new InvertedLists(cPtr, false);
  }

  public void setOwn_invlists(boolean value) {
    swigfaissJNI.IndexIVF_own_invlists_set(swigCPtr, this, value);
  }

  public boolean getOwn_invlists() {
    return swigfaissJNI.IndexIVF_own_invlists_get(swigCPtr, this);
  }

  public void setCode_size(long value) {
    swigfaissJNI.IndexIVF_code_size_set(swigCPtr, this, value);
  }

  public long getCode_size() {
    return swigfaissJNI.IndexIVF_code_size_get(swigCPtr, this);
  }

  public void setNprobe(long value) {
    swigfaissJNI.IndexIVF_nprobe_set(swigCPtr, this, value);
  }

  public long getNprobe() {
    return swigfaissJNI.IndexIVF_nprobe_get(swigCPtr, this);
  }

  public void setMax_codes(long value) {
    swigfaissJNI.IndexIVF_max_codes_set(swigCPtr, this, value);
  }

  public long getMax_codes() {
    return swigfaissJNI.IndexIVF_max_codes_get(swigCPtr, this);
  }

  public void setParallel_mode(int value) {
    swigfaissJNI.IndexIVF_parallel_mode_set(swigCPtr, this, value);
  }

  public int getParallel_mode() {
    return swigfaissJNI.IndexIVF_parallel_mode_get(swigCPtr, this);
  }

  public void setMaintain_direct_map(boolean value) {
    swigfaissJNI.IndexIVF_maintain_direct_map_set(swigCPtr, this, value);
  }

  public boolean getMaintain_direct_map() {
    return swigfaissJNI.IndexIVF_maintain_direct_map_get(swigCPtr, this);
  }

  public void setDirect_map(SWIGTYPE_p_std__vectorT_long_long_t value) {
    swigfaissJNI.IndexIVF_direct_map_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_long_long_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_long_long_t getDirect_map() {
    long cPtr = swigfaissJNI.IndexIVF_direct_map_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_long_long_t(cPtr, false);
  }

  public void reset() {
    swigfaissJNI.IndexIVF_reset(swigCPtr, this);
  }

  public void train(long n, SWIGTYPE_p_float x) {
    swigfaissJNI.IndexIVF_train(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x));
  }

  public void add(long n, SWIGTYPE_p_float x) {
    swigfaissJNI.IndexIVF_add(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x));
  }

  public void add_with_ids(long n, SWIGTYPE_p_float x, SWIGTYPE_p_long_long xids) {
    swigfaissJNI.IndexIVF_add_with_ids(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_long_long.getCPtr(xids));
  }

  public void encode_vectors(long n, SWIGTYPE_p_float x, SWIGTYPE_p_long_long list_nos, SWIGTYPE_p_unsigned_char codes) {
    swigfaissJNI.IndexIVF_encode_vectors(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_long_long.getCPtr(list_nos), SWIGTYPE_p_unsigned_char.getCPtr(codes));
  }

  public void train_residual(long n, SWIGTYPE_p_float x) {
    swigfaissJNI.IndexIVF_train_residual(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x));
  }

  public void search_preassigned(long n, SWIGTYPE_p_float x, long k, SWIGTYPE_p_long_long assign, SWIGTYPE_p_float centroid_dis, SWIGTYPE_p_float distances, SWIGTYPE_p_long_long labels, boolean store_pairs, IVFSearchParameters params) {
    swigfaissJNI.IndexIVF_search_preassigned__SWIG_0(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), k, SWIGTYPE_p_long_long.getCPtr(assign), SWIGTYPE_p_float.getCPtr(centroid_dis), SWIGTYPE_p_float.getCPtr(distances), SWIGTYPE_p_long_long.getCPtr(labels), store_pairs, IVFSearchParameters.getCPtr(params), params);
  }

  public void search_preassigned(long n, SWIGTYPE_p_float x, long k, SWIGTYPE_p_long_long assign, SWIGTYPE_p_float centroid_dis, SWIGTYPE_p_float distances, SWIGTYPE_p_long_long labels, boolean store_pairs) {
    swigfaissJNI.IndexIVF_search_preassigned__SWIG_1(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), k, SWIGTYPE_p_long_long.getCPtr(assign), SWIGTYPE_p_float.getCPtr(centroid_dis), SWIGTYPE_p_float.getCPtr(distances), SWIGTYPE_p_long_long.getCPtr(labels), store_pairs);
  }

  public void search(long n, SWIGTYPE_p_float x, long k, SWIGTYPE_p_float distances, SWIGTYPE_p_long_long labels) {
    swigfaissJNI.IndexIVF_search(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), k, SWIGTYPE_p_float.getCPtr(distances), SWIGTYPE_p_long_long.getCPtr(labels));
  }

  public void range_search(long n, SWIGTYPE_p_float x, float radius, RangeSearchResult result) {
    swigfaissJNI.IndexIVF_range_search(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), radius, RangeSearchResult.getCPtr(result), result);
  }

  public void range_search_preassigned(long nx, SWIGTYPE_p_float x, float radius, SWIGTYPE_p_long_long keys, SWIGTYPE_p_float coarse_dis, RangeSearchResult result) {
    swigfaissJNI.IndexIVF_range_search_preassigned(swigCPtr, this, nx, SWIGTYPE_p_float.getCPtr(x), radius, SWIGTYPE_p_long_long.getCPtr(keys), SWIGTYPE_p_float.getCPtr(coarse_dis), RangeSearchResult.getCPtr(result), result);
  }

  public SWIGTYPE_p_faiss__InvertedListScanner get_InvertedListScanner(boolean store_pairs) {
    long cPtr = swigfaissJNI.IndexIVF_get_InvertedListScanner__SWIG_0(swigCPtr, this, store_pairs);
    return (cPtr == 0) ? null : new SWIGTYPE_p_faiss__InvertedListScanner(cPtr, false);
  }

  public SWIGTYPE_p_faiss__InvertedListScanner get_InvertedListScanner() {
    long cPtr = swigfaissJNI.IndexIVF_get_InvertedListScanner__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_faiss__InvertedListScanner(cPtr, false);
  }

  public void reconstruct(long key, SWIGTYPE_p_float recons) {
    swigfaissJNI.IndexIVF_reconstruct(swigCPtr, this, key, SWIGTYPE_p_float.getCPtr(recons));
  }

  public void reconstruct_n(long i0, long ni, SWIGTYPE_p_float recons) {
    swigfaissJNI.IndexIVF_reconstruct_n(swigCPtr, this, i0, ni, SWIGTYPE_p_float.getCPtr(recons));
  }

  public void search_and_reconstruct(long n, SWIGTYPE_p_float x, long k, SWIGTYPE_p_float distances, SWIGTYPE_p_long_long labels, SWIGTYPE_p_float recons) {
    swigfaissJNI.IndexIVF_search_and_reconstruct(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), k, SWIGTYPE_p_float.getCPtr(distances), SWIGTYPE_p_long_long.getCPtr(labels), SWIGTYPE_p_float.getCPtr(recons));
  }

  public void reconstruct_from_offset(long list_no, long offset, SWIGTYPE_p_float recons) {
    swigfaissJNI.IndexIVF_reconstruct_from_offset(swigCPtr, this, list_no, offset, SWIGTYPE_p_float.getCPtr(recons));
  }

  public long remove_ids(IDSelector sel) {
    return swigfaissJNI.IndexIVF_remove_ids(swigCPtr, this, IDSelector.getCPtr(sel), sel);
  }

  public void check_compatible_for_merge(IndexIVF other) {
    swigfaissJNI.IndexIVF_check_compatible_for_merge(swigCPtr, this, IndexIVF.getCPtr(other), other);
  }

  public void merge_from(IndexIVF other, long add_id) {
    swigfaissJNI.IndexIVF_merge_from(swigCPtr, this, IndexIVF.getCPtr(other), other, add_id);
  }

  public void copy_subset_to(IndexIVF other, int subset_type, long a1, long a2) {
    swigfaissJNI.IndexIVF_copy_subset_to(swigCPtr, this, IndexIVF.getCPtr(other), other, subset_type, a1, a2);
  }

  public long get_list_size(long list_no) {
    return swigfaissJNI.IndexIVF_get_list_size(swigCPtr, this, list_no);
  }

  public void make_direct_map(boolean new_maintain_direct_map) {
    swigfaissJNI.IndexIVF_make_direct_map__SWIG_0(swigCPtr, this, new_maintain_direct_map);
  }

  public void make_direct_map() {
    swigfaissJNI.IndexIVF_make_direct_map__SWIG_1(swigCPtr, this);
  }

  public void replace_invlists(InvertedLists il, boolean own) {
    swigfaissJNI.IndexIVF_replace_invlists__SWIG_0(swigCPtr, this, InvertedLists.getCPtr(il), il, own);
  }

  public void replace_invlists(InvertedLists il) {
    swigfaissJNI.IndexIVF_replace_invlists__SWIG_1(swigCPtr, this, InvertedLists.getCPtr(il), il);
  }

  public void setQuantizer(Index value) {
    swigfaissJNI.IndexIVF_quantizer_set(swigCPtr, this, Index.getCPtr(value), value);
  }

  public Index getQuantizer() {
    long cPtr = swigfaissJNI.IndexIVF_quantizer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Index(cPtr, false);
  }

  public void setNlist(long value) {
    swigfaissJNI.IndexIVF_nlist_set(swigCPtr, this, value);
  }

  public long getNlist() {
    return swigfaissJNI.IndexIVF_nlist_get(swigCPtr, this);
  }

  public void setQuantizer_trains_alone(char value) {
    swigfaissJNI.IndexIVF_quantizer_trains_alone_set(swigCPtr, this, value);
  }

  public char getQuantizer_trains_alone() {
    return swigfaissJNI.IndexIVF_quantizer_trains_alone_get(swigCPtr, this);
  }

  public void setOwn_fields(boolean value) {
    swigfaissJNI.IndexIVF_own_fields_set(swigCPtr, this, value);
  }

  public boolean getOwn_fields() {
    return swigfaissJNI.IndexIVF_own_fields_get(swigCPtr, this);
  }

  public void setCp(ClusteringParameters value) {
    swigfaissJNI.IndexIVF_cp_set(swigCPtr, this, ClusteringParameters.getCPtr(value), value);
  }

  public ClusteringParameters getCp() {
    long cPtr = swigfaissJNI.IndexIVF_cp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ClusteringParameters(cPtr, false);
  }

  public void setClustering_index(Index value) {
    swigfaissJNI.IndexIVF_clustering_index_set(swigCPtr, this, Index.getCPtr(value), value);
  }

  public Index getClustering_index() {
    long cPtr = swigfaissJNI.IndexIVF_clustering_index_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Index(cPtr, false);
  }

  public void train_q1(long n, SWIGTYPE_p_float x, boolean verbose, MetricType metric_type) {
    swigfaissJNI.IndexIVF_train_q1(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), verbose, metric_type.swigValue());
  }

}
