/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bj58.spider.faiss;

public class IndexBinaryReplicas extends ThreadedIndexBaseBinary {
  private transient long swigCPtr;

  protected IndexBinaryReplicas(long cPtr, boolean cMemoryOwn) {
    super(swigfaissJNI.IndexBinaryReplicas_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexBinaryReplicas obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_IndexBinaryReplicas(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IndexBinaryReplicas(boolean threaded) {
    this(swigfaissJNI.new_IndexBinaryReplicas__SWIG_0(threaded), true);
  }

  public IndexBinaryReplicas() {
    this(swigfaissJNI.new_IndexBinaryReplicas__SWIG_1(), true);
  }

//  public IndexBinaryReplicas(long d, boolean threaded) {
//    this(swigfaissJNI.new_IndexBinaryReplicas__SWIG_2(d, threaded), true);
//  }

  public IndexBinaryReplicas(long d) {
    this(swigfaissJNI.new_IndexBinaryReplicas__SWIG_3(d), true);
  }

  public IndexBinaryReplicas(int d, boolean threaded) {
    this(swigfaissJNI.new_IndexBinaryReplicas__SWIG_4(d, threaded), true);
  }

  public IndexBinaryReplicas(int d) {
    this(swigfaissJNI.new_IndexBinaryReplicas__SWIG_5(d), true);
  }

  public void add_replica(IndexBinary index) {
    swigfaissJNI.IndexBinaryReplicas_add_replica(swigCPtr, this, IndexBinary.getCPtr(index), index);
  }

  public void remove_replica(IndexBinary index) {
    swigfaissJNI.IndexBinaryReplicas_remove_replica(swigCPtr, this, IndexBinary.getCPtr(index), index);
  }

  public void train(long n, SWIGTYPE_p_unsigned_char x) {
    swigfaissJNI.IndexBinaryReplicas_train(swigCPtr, this, n, SWIGTYPE_p_unsigned_char.getCPtr(x));
  }

  public void add(long n, SWIGTYPE_p_unsigned_char x) {
    swigfaissJNI.IndexBinaryReplicas_add(swigCPtr, this, n, SWIGTYPE_p_unsigned_char.getCPtr(x));
  }

  public void search(long n, SWIGTYPE_p_unsigned_char x, long k, SWIGTYPE_p_int distances, SWIGTYPE_p_long_long labels) {
    swigfaissJNI.IndexBinaryReplicas_search(swigCPtr, this, n, SWIGTYPE_p_unsigned_char.getCPtr(x), k, SWIGTYPE_p_int.getCPtr(distances), SWIGTYPE_p_long_long.getCPtr(labels));
  }

  public void reconstruct(long arg0, SWIGTYPE_p_unsigned_char v) {
    swigfaissJNI.IndexBinaryReplicas_reconstruct(swigCPtr, this, arg0, SWIGTYPE_p_unsigned_char.getCPtr(v));
  }

}
