/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bj58.spider.faiss;

public interface Level1Quantizer {
  long Level1Quantizer_GetInterfaceCPtr();
  void setQuantizer(Index value);
  Index getQuantizer();
  void setNlist(long value);
  long getNlist();
  void setQuantizer_trains_alone(char value);
  char getQuantizer_trains_alone();
  void setOwn_fields(boolean value);
  boolean getOwn_fields();
  void setCp(ClusteringParameters value);
  ClusteringParameters getCp();
  void setClustering_index(Index value);
  Index getClustering_index();
  void train_q1(long n, SWIGTYPE_p_float x, boolean verbose, MetricType metric_type);
}
