/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bj58.spider.faiss;

public class longlongArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected longlongArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(longlongArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_longlongArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public longlongArray(int nelements) {
    this(swigfaissJNI.new_longlongArray(nelements), true);
  }

  public long getitem(int index) {
    return swigfaissJNI.longlongArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, long value) {
    swigfaissJNI.longlongArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_long_long cast() {
    long cPtr = swigfaissJNI.longlongArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

  public static longlongArray frompointer(SWIGTYPE_p_long_long t) {
    long cPtr = swigfaissJNI.longlongArray_frompointer(SWIGTYPE_p_long_long.getCPtr(t));
    return (cPtr == 0) ? null : new longlongArray(cPtr, false);
  }

}
