/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bj58.spider.faiss;

public class VectorIOReader extends IOReader {
  private transient long swigCPtr;

  protected VectorIOReader(long cPtr, boolean cMemoryOwn) {
    super(swigfaissJNI.VectorIOReader_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorIOReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_VectorIOReader(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setData(ByteVector value) {
    swigfaissJNI.VectorIOReader_data_set(swigCPtr, this, ByteVector.getCPtr(value), value);
  }

  public ByteVector getData() {
    long cPtr = swigfaissJNI.VectorIOReader_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ByteVector(cPtr, false);
  }

  public void setRp(long value) {
    swigfaissJNI.VectorIOReader_rp_set(swigCPtr, this, value);
  }

  public long getRp() {
    return swigfaissJNI.VectorIOReader_rp_get(swigCPtr, this);
  }

  public long __operator_small__(SWIGTYPE_p_void ptr, long size, long nitems) {
    return swigfaissJNI.VectorIOReader___operator_small__(swigCPtr, this, SWIGTYPE_p_void.getCPtr(ptr), size, nitems);
  }

  public VectorIOReader() {
    this(swigfaissJNI.new_VectorIOReader(), true);
  }

}
